name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          client/package-lock.json

    - name: Install root dependencies
      run: npm ci
      
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci

    - name: Run client lint
      working-directory: ./client
      run: npm run lint

    - name: Build client
      working-directory: ./client
      run: npm run build

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: 'server/requirements.txt'

    - name: Install Python dependencies
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Ruff checks
      working-directory: ./server
      run: python -m ruff check .

    - name: Test server startup
      run: |
        timeout 5 uvicorn main:app || code=$?; if [ $code -eq 124 ]; then exit 0; else exit $code; fi 